# Generated by Django 4.1.2 on 2022-10-26 16:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('date_upload', models.DateField(default=datetime.date.today)),
                ('time_limit', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('F', 'Finished'), ('U', 'Updating')], default='U', max_length=1)),
                ('tutor_id', models.IntegerField(null=True)),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('cover_image', models.ImageField(null=True, upload_to='Course/file/covers')),
                ('hashtag', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
