# Generated by Django 4.1.2 on 2022-11-03 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by_system', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='section',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='documentLink',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='videoLink',
            new_name='video',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='course.category'),
        ),
    ]
