# Generated by Django 4.1.2 on 2023-01-01 19:17

import course.models.section
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedcourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='ownedcourse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='document',
            field=models.FileField(max_length=500, null=True, upload_to=course.models.section.get_section_path),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.FileField(max_length=500, null=True, upload_to=course.models.section.get_section_path),
        ),
    ]
