# Generated by Django 4.1.2 on 2022-12-21 08:40

import course.models.section
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='document',
            field=models.FileField(max_length=500, upload_to=course.models.section.get_section_path),
        ),
    ]
