# Generated by Django 4.1.2 on 2022-10-25 16:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_hashtag_course_name_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_upload',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='course',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
