# Generated by Django 4.1.2 on 2023-01-05 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_id_ownedcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
