# Generated by Django 4.1.2 on 2022-11-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_ownedcourse'),
        ('course', '0003_category_rename_courseid_section_course_and_more'),
    ]

    operations = [
    ]
