# Generated by Django 4.1.2 on 2022-10-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_upload',
        ),
        migrations.RemoveField(
            model_name='course',
            name='upload_id',
        ),
    ]
