# Generated by Django 4.1.2 on 2022-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_course_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='Course/file/covers'),
        ),
    ]
